# Aula 01 - Numpy
---

<img src="https://lc-public-assets.s3.sa-east-1.amazonaws.com/images/Logos/logoLcPng.webp" width="220px" style="position: absolute; top: 15px; right: 20px; border-radius: 5px;" />

1. Instalação
2. Criação de arrays 1D e 2D
3. Atributos
4. Indexação e slices
5. Criação automática de arrays
6. Métodos estatísticos
7. Outros métodos
8. Máscaras

## 1. Instalação

In [1]:
!pip install numpy

In [4]:
import numpy as np

## 2. Criação de Arrays 1D e 2D

In [2]:
lista = [1, 2, 3, 4, 5]

In [3]:
type(lista)

list

In [5]:
np.array([1, 2, 3])

array([1, 2, 3])

In [6]:
array = np.array([1, 2, 3])

In [7]:
lista = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # lista bidimensional

In [8]:
lista_2D = []

lista_2D.append([1, 2, 3])

print(lista_2D)

[[1, 2, 3]]


In [9]:
matriz = np.array(lista)

In [10]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 3. Atributos

#### `ndim`

In [12]:
array

array([1, 2, 3])

In [13]:
array.ndim # A dimensão do array (1D)

1

In [14]:
matriz.ndim # A dimensão do matriz (2D)

2

#### `shape`

In [15]:
array.shape

(3,)

In [16]:
matriz.shape

(3, 3)

In [ ]:
# Imagem colorida HD
(1280, 720, 3)

In [17]:
1280 * 720 * 3

2764800

#### `size`

In [20]:
array.size

3

In [21]:
matriz.size

9

#### `dtype`

In [22]:
array.dtype

dtype('int64')

In [23]:
matriz.dtype

dtype('int64')

In [28]:
array = np.array([1, 2, 3.0], dtype='float')

array.dtype

dtype('float64')

In [29]:
array.itemsize

8

## 4. Indexação e slices 

In [30]:
array

array([1., 2., 3.])

In [31]:
array[0]

1.0

In [32]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
matriz[1][2]

6

In [38]:
matriz[1, 2]

6

In [39]:
array[0:2]

array([1., 2.])

In [40]:
array[-1]

3.0

## 5. Criação Automática de Arrays

#### `arange`

In [42]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [43]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(10, 21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [45]:
np.arange(10, 21, 3)

array([10, 13, 16, 19])

In [46]:
import math

math.pi

3.141592653589793

In [48]:
eixo_x = np.arange(0, 2 * np.pi, 0.01)

In [49]:
type(eixo_x)

numpy.ndarray

In [50]:
eixo_x.shape

(629,)

#### `linspace`

In [55]:
np.linspace(1, 10, 100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [56]:
np.linspace(0, 10, 100, endpoint=False)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

#### `zeros`

In [57]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### `ones`

In [59]:
ones = np.ones(10)

In [60]:
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [61]:
ones = np.ones((10, 10))

In [62]:
ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### `full`

In [63]:
np.full((5, 5), 40)

array([[40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40]])

In [64]:
np.ones((5, 5)) * 40

array([[40., 40., 40., 40., 40.],
       [40., 40., 40., 40., 40.],
       [40., 40., 40., 40., 40.],
       [40., 40., 40., 40., 40.],
       [40., 40., 40., 40., 40.]])

#### `full_like`

In [65]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
np.full_like(matriz, 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

#### `rand`

In [75]:
np.random.rand(3)

array([0.02524285, 0.79304162, 0.71928731])

In [76]:
np.random.rand(3, 3)

array([[0.64035838, 0.5394689 , 0.00218943],
       [0.38155036, 0.2055113 , 0.02909579],
       [0.74880093, 0.74205113, 0.26227172]])

In [83]:
np.random.rand(3, 3) * 10

array([[9.3232079 , 3.4650337 , 5.27153913],
       [0.92335192, 5.3287525 , 7.94870973],
       [8.44841902, 8.55648548, 6.48873178]])

#### `randn`

In [77]:
np.random.randn(10)

array([ 1.7459381 ,  0.42870946, -0.45344745,  0.91201912,  0.02170084,
       -0.98552599,  2.23086856, -0.23902189, -1.15237923, -0.95936845])

In [82]:
np.random.randn(10) * 100

array([  7.73944896,  30.92011694, -47.48070397,  -9.39828591,
        57.40389427, -35.54736996, -88.05178992, -36.48123158,
        62.22387689, -42.68775392])

#### `randint`

In [79]:
import random

random.randint(1, 10)

8

In [80]:
np.random.randint(1, 20, 100)

array([13,  9,  7, 15, 19,  3, 12,  6,  9, 10, 13, 11, 19, 14,  8,  9, 17,
        6,  3,  5, 12,  6, 17,  8,  7,  5, 18,  4,  4,  3,  1,  6, 15, 13,
        8, 18,  4,  8,  7,  9, 18, 19,  2,  6,  7, 10, 16,  3,  9,  4,  8,
        3,  2, 13, 10,  7,  1,  4,  4, 11, 12,  6, 15, 17, 16, 18, 17,  6,
        2, 13,  7,  7, 10, 17, 11,  5, 11,  6,  5,  1, 12,  5, 13,  3,  1,
       12,  8,  6,  5, 12, 15, 18,  4,  8, 18,  1,  8, 18,  9,  2])

In [81]:
np.random.randint(1, 20, (10, 10))

array([[17, 18, 15, 17, 12, 10,  2,  2,  9,  9],
       [ 1,  1, 11, 18,  5,  3, 11,  3,  2,  9],
       [10,  4, 18, 14,  2,  3, 18, 14, 13, 11],
       [12, 10, 17, 12,  2, 12,  7,  5,  7,  2],
       [10,  1, 13, 14,  1, 12, 17, 18, 16,  3],
       [ 8,  2, 11, 16,  6,  4,  4, 15, 12,  2],
       [16,  6, 19, 13,  6, 15, 19,  5,  4, 19],
       [18, 10,  3,  9,  4,  3,  1, 10,  6, 18],
       [17,  5,  3,  1, 16, 13, 11,  5,  8, 19],
       [ 9,  7,  4,  6,  3, 17,  2, 11,  2,  9]])

#### `uniform`

In [84]:
np.random.uniform(0, 100, 20)

array([28.88548916,  1.30627362, 63.99045579,  9.40280537, 41.77195958,
       64.18478248, 64.41450559, 38.61755299, 52.96176195, 39.16964842,
       69.66940432,  3.32398736, 34.63192142,  8.55761569, 54.08163883,
       70.99283537, 62.98404881, 42.74856887, 73.22242529, 68.13766298])

#### `identity`

In [87]:
np.identity(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### `diag`

In [89]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

## 6. Métodos estatísticos e outros

#### `sum`

In [91]:
sum([1, 2, 3])

6

In [92]:
array

array([1., 2., 3.])

In [93]:
array.sum()

6.0

In [94]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
matriz.sum()

45

#### `max` e `argmax`

In [96]:
array.max()

3.0

In [97]:
array.argmax()

2

In [98]:
array

array([1., 2., 3.])

#### `min` e `argmin`

In [99]:
array.min()

1.0

In [100]:
array.argmin()

0

#### `mean`

In [101]:
array.mean()

2.0

#### `np.repeat`

#### `np.transpose`

#### `reshape`

#### `np.vstack`

#### `np.hstack`

## 7. Máscaras